title: Nick Lambson
description: > # this means to ignore newlines until "baseurl:"
  Nick Lambson is a localization engineer and teacher living in Beijing, China.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "nicklambson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Nick Lambson # add your name
author-img: nick-lambson-portrait.jpg # add your photo
about-author: "Senior Foreign Teacher at Beijing Language and Culture University

Staff Localization Engineer at MediaLocate

Bachelor of Music in Sound Recording Technology, double major in Russian Studies from Brigham Young University

Master of Arts in Translation and Localization Management from Middlebury Institute of International Studies at Monterey"

social-github: nicklambson # add your Github handle
social-linkedin: nicklambson
social-email: nicklambson_at_blcu_dot_edu_dot_cn@spam_prevention.com

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
