title: Nick Lambson
description: > # this means to ignore newlines until "baseurl:"
  Nick Lambson is a localization engineer and teacher living in Beijing, China.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "nicklambson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Nick Lambson # add your name
author-img: nick-lambson-portrait.jpg # add your photo
about-author: I am a localization engineer and teacher. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: nicklambson # add your Github handle
social-linkedin: nicklambson
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
